### ISSUE TITLE
mbtiles2kaps.py", line 175, in <module> subprocess.call(pngquantcommand)

### ISSUE THREAD

**Issue by Pacific8118** [seandepagnier/mbtiles-nautical-tools#2]
Hello,
I came across those utilities and wanted to use them to create KAP files for OpenCPN.
Very usefull but error when launching Mbtiles2kap.py :

I installed accordingly but got following error messages :
( I have no understanding of Python but I managed to launch it with the debugger to get as much as possible information ( further below ))
Without debugger :
frederic@ubuntu-VirtualBox:~/mbtiles-nautical-tools$ sudo ./mbtiles2kaps.py ../manchelarge.mbtiles /home/frederic/manche
9 charts for zoom 9                              
16 charts for zoom 10                              
31 charts for zoom 11                              
65 charts for zoom 12                              
128 charts for zoom 13                              
will generate 249 charts
0.0%  converting  (-6.328125, 48.922499, 0.703125, 50.289339) 9 30 tiles
pngquant 127 -f --ext .png /home/frederic/manche/9/0.png
Traceback (most recent call last):
  File "./mbtiles2kaps.py", line 175, in <module>
    subprocess.call(pngquantcommand)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
frederic@ubuntu-VirtualBox:~/mbtiles-nautical-tools$ 

With Debugger :
frederic@ubuntu-VirtualBox:~/mbtiles-nautical-tools$ sudo python -m pdb mbtiles2kaps.py ../manchelarge.mbtiles /home/frederic/manche 
> /home/frederic/mbtiles-nautical-tools/mbtiles2kaps.py(10)<module>()
-> import os
(Pdb) continue
9 charts for zoom 9                              
16 charts for zoom 10                              
31 charts for zoom 11                              
65 charts for zoom 12                              
128 charts for zoom 13                              
will generate 249 charts
0.0%  converting  (-6.328125, 48.922499, 0.703125, 50.289339) 9 30 tiles
pngquant 127 -f --ext .png /home/frederic/manche/9/0.png
Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "mbtiles2kaps.py", line 10, in <module>
    import os
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /usr/lib/python2.7/subprocess.py(1047)_execute_child()
-> raise child_exception
(Pdb) continue
Post mortem debugger finished. The mbtiles2kaps.py will be restarted

**Comment by seandepagnier** [comment]
do you have the command "pngquant" installed and available in the path?

**Comment by Pacific8118** [comment]
My mistake I did install the pngquant.py wrapper instead of the pngquant-bin.
It works now !!!!
Thank you sir.
